language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r aws-ppang-ec2 *
  - mkdir -p deploy
  - mv aws-ppang-ec2.zip deploy/aws-ppang-ec2.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: aws-ppang-s3 # s3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private 으로
    local_dir: deploy # before_deploy에서 생산한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값

    bucket: aws-ppang-s3 # s3 버킷
    key: aws-ppang-ec2.zip # 빌드 파일을 압축해서 전달

    bundle_type: zip # 압축 확장자
    application: aws-ppang-deploy # 웹 콘솔에서 등록한 codeDeploy 애플리케이션

    deployment_group: aws-ppang-deploy-group # 웹 콘솔에서 등록한 codeDeploy 배포그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - wjdrhkd456@gmail.com


